# This is a Docker Compose file https://docs.docker.com/compose/

# Run "docker compose up" to run the application

version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:8000"
#    env_file:
#    - compose.env # docker compose will use .env automatically or you can specify one here
