name: Update Dependencies

on:
  schedule:
    - cron: '33 14 * * *'
  workflow_dispatch: {}

permissions:
  pull-requests: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Dependencies
      run: |
        cd src
        python -m pip install --upgrade pip pip-tools
        pip install -r requirements.txt
        
    - name: Update Dependencies
      run: |
        cd src
        pip-compile --upgrade --resolver=backtracking

    - name: Commit and push
      env:
        CI_COMMIT_MESSAGE: Update Dependencies
        CI_COMMIT_AUTHOR: Dependency updater
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "ollytheninja@users.noreply.github.com"
        
        git checkout -B pip-deps
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push -f -u origin pip-deps

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto dependency update
        branch: pip-deps
        create_branch: true

    - name: Create PR
      uses: devops-infra/action-pull-request@v0.4.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: pip-deps
        target_branch: main
        title: Update python dependencies
        body: "**Automated dependency update**"
        reviewer: ollytheninja
        assignee: ollytheninja
